### ISSUE TITLE
[COPY EDIT] Remove "a"

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#247]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/functions/naming-functions.html#use-verb-noun-pairs-when-applicable

## Issue

Remove "a"

## (Optional) Screenshot

<img width="803" alt="Screen Shot 2019-10-21 at 1 40 06 PM" src="https://user-images.githubusercontent.com/17087389/67235694-3906a600-f40d-11e9-8c87-936f9bda2a62.png">

**Comment by jimflores5** [comment]
There is another fix required in this paragraph.  "...what a function does," or "...what functions do."

Two possible fixes:
1) Singular option = "Therefore, using a verb/noun pair can go a long way toward making it clear what a function does."
2) Plural option = "Therefore, using verb/noun pairs can go a long way toward making it clear what functions do."

I prefer the first option, since it matches the singular "function" and "verb" in the surrounding sentences.
