### ISSUE TITLE
Feedback on Mars Rover

### ISSUE THREAD

**Issue by gildedgardenia** [LaunchCodeEducation/intro-to-professional-web-dev#305]
Some students are reading through the background information on what each class should do and trying to code the class before writing the tests. Clarify instructions to remind students that these are the desired characteristics of the class not something to start coding yet.

**Comment by gildedgardenia** [comment]
Issue #276 includes additional feedback as well.

**Comment by gildedgardenia** [comment]
``deepEqual`` is better suited to Test 10

**Comment by jimflores5** [comment]
More feedback collected by the Sept LC101 CEM:
1) Overall, reduce the size of the assignment (13 tests is overwhelming the students).
2) In regards to point 1: What are the core concepts we want the students to learn, and what is the smallest number of tests that need to be completed to demonstrate understanding?
3) The Jasmine `assert` method needs a better introduction before moving into the assignment.  Currently, it seems like we drop a fair amount of new ideas/content into the assignment.  Some prior knowledge/experience is missing.
4) Be really explicit with the instructions for the `Message` class.  Many students are hard-coding statements rather than doing what we intended.  The students are confused about how to approach the class.  We need to revise the instructions to better explain what we want them to do.

**Comment by CarlyLanglois** [comment]
closing this as we're preparing for another round of improvements to the assignment
