### ISSUE TITLE
[comments] 1.3 About LaunchCode Program

### ISSUE THREAD

**Issue by linwang929** [LaunchCodeEducation/intro-to-professional-web-dev#48]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/introduction/about-this-class.html#in-class-time

## Issue

Was it intentional to leave out instructor and teaching assistants? If so, I think it is still worth mentioning the availability of a dedicated course staff so that readers understand that someone is in class to facilitate these activities. It may make students feel more supported since they haven't yet been to a class (supposedly) at this time.

**Comment by welzie** [comment]
@linwang929 What do you think about this? Please ignore the weird formatting, all the content is written in a mark down like syntax known as RST.

In-class Time
-------------

In class you will meet many fellow students on the same learning journey as you. We encourage students to engage and encourage each other
throughout the class.

There will also be an instructor and teaching assistants, this dedicated staff facilitates the activities and provides
support to the students.

Large Group Time
^^^^^^^^^^^^^^^^

During the large group time, the whole class participates in the lesson, lead by the instructor, and takes time for Q&A about the prep work.
This is a time for us to review examples as a group and shore up concepts from the prep work.

Small Group Time
^^^^^^^^^^^^^^^^

After the large group time, we will break up into small groups, lead by a teaching assistant. During small group time, we will do in-class coding activities called studios.
This time is equally as important as large group time because it is time for individual support and a place where you can feel comfortable talking openly about concepts you are struggling with.
