### ISSUE TITLE
[COPY EDIT] JS not the only web language

### ISSUE THREAD

**Issue by dcmorse** [LaunchCodeEducation/intro-to-professional-web-dev#60]
## Permalink

https://education.launchcode.org/intro-to-professional-web-dev/chapters/how-programs-work/the-javascript-language.html

## Issue

> JavaScript is very good at this because it is the only language that runs inside a web browser. This means that the code loads at the same time as a web page.

The first sentence is not true. WebAssembly is real and in the big-4 browsers. Also, compile-to-js languages like Typescript, Elm, and Clojurescript are common, and will also compile to WebAssembly. I would substitute "most popular for "only". 

The other wording strikes me as odd too, but I can't quite put my finger on it. 

## (Optional) Screenshow

(If helpful, add a screenshot.)

**Comment by jimflores5** [comment]
Dave, the original intent was to avoid getting too far into the weeds with which languages run in the browser. How about something like:
"**JavaScript** is one of many programming languages, each of which serves
different purposes. Programmers mainly use JavaScript for web development,
and it is currently the most popular language that runs inside a web browser.
*Running inside the browser* means that the code loads at the same time as a
web page."

**Comment by dcmorse** [comment]
I like the first two sentences a lot better. 

Maybe the last sentence still needs something...It's not just that the code loads at the same time as the web page, but that the code can **interact** with the web page. It can add text, change colors, and create animations. It can react to mouse clicks. It can even fetch instant messages or weather information through a web api. If HTML is the skeleton of a web page, and css is the clothing, then javascript is the central nervous system.

**Comment by jimflores5** [comment]
Thanks!  Here is the next iteration.  I really liked your central nervous system analogy, but since this is the intro material, the students may not know about HTML vs. CSS yet.  Let me know what you think.

**JavaScript** is one of many programming languages, each of which serves
different purposes. Programmers mainly use JavaScript for web development,
and it is currently the most popular language that runs inside a web browser.
*Running inside the browser* means that the code loads at the same time as a
web page and can modify the content. JavaScript can add or remove text, change
colors, produce animations, and react to mouse and keyboard clicks. This makes
the web page *dynamic*---it responds to user actions in real time, and changes
occur without having to refresh the page.

This cool feature allows immediate updates your profile when you post a status,
change the color of the “Submit” button after you complete a form, generate
a map when you request directions, or create a sparkly trail that follows the
mouse pointer. All of the changes to what you see on the web page are part of
**front end** development. They are present on your computer.

**Comment by dcmorse** [comment]
:+1: 
I'm on board for that. 

> This cool feature allows immediate updates **to** your profile when you post a status,...

:point_up: minor wording addition

**Comment by jimflores5** [comment]
Thanks x 3.  Fixed typo and closed issue.
